name: "Build & Publish NFT Image & Artifacts"

on:
  workflow_dispatch:
    # Just run it

  push:
    branches:
      - "main"
      - "nft-artifacts"
    tags:
      - "v*"
      - "!**-test"
      - "!**-dev"

jobs:
  upload-to-gh-artifacts:
    runs-on: ubuntu-latest
    name: Upload NFT Artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nft-artifacts
          path: |
            ./wasm
            ./candid

  upload-to-gcs:
    if: github.ref_name == 'nft-artifacts' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Artifacts tag
        run: echo "ARTIFACTS_TAG=${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}" >> $GITHUB_ENV

      - name: Tar archive artifacts
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          files: |
            candid
            wasm
          outPath: nft-artifacts-${{ env.ARTIFACTS_TAG }}.tar.gz

      - name: Auth gcloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_JSON_DOCS_TOKEN }}

      - name: Upload to gcs
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: nft-artifacts-${{ env.ARTIFACTS_TAG }}.tar.gz
          destination: dfx-server_ic/nft-artifacts
